FROM python:3.13.3-slim-bookworm

# create directory for the app user
RUN mkdir -p /home/app

#create the app user
RUN addgroup --system app && adduser --system --group app

#create th appropriate directories
ENV HOME=/home/app
ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

COPY --from=ghcr.io/astral-sh/uv:0.9.21 /uv /uvx /bin/

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
# ENV UV_PROJECT_ENVIRONMENT=${APP_HOME}/.venv
# ENV UV_NO_CACHE=true
# ENV UV_LINK_MODE=copy
ENV ENVIRONMENT=prod
ENV TESTING=0

RUN apt-get update \
  && apt-get -y install netcat-traditional gcc postgresql \
  && apt-get clean

COPY pyproject.toml uv.lock ./
RUN uv sync
RUN uv add "uvicorn[standard]==0.34.1"

COPY . .

RUN chown -R app:app $APP_HOME

USER app

CMD gunicorn --bind 0.0.0.0:$PORT app.main:app -k uvicorn.workers.UvicornWorker
